[tools]
  # @config-manager:start standard
  1password-cli = "latest"
  bat = "latest"
  coreutils = "latest"
  cosign = "latest"
  # dasel
  direnv = "latest"
  dotenvx = "latest"
  editorconfig-checker = "latest"
  fd = "latest"
  fzf = "latest"
  git-cliff = "latest"
  git-filter-repo = "latest"
  git-lfs = "latest"
  go = "latest"
  gum = "latest"
  hk = "latest"
  jq = "latest"
  lychee = "latest"
  osv-scanner = "latest"
  pandoc = "latest"
  pitchfork = "latest"
  prettier = "latest"
  rg = "latest"
  rumdl = "latest"
  shellcheck = "latest"
  shfmt = "latest"
  taplo = "latest"
  task = "latest"
  trivy = "latest"
  trufflehog = "latest"
  yamlfmt = "latest"
  # @config-manager:end standard
