#-------------------------------------------------------------------------------
# DEFAULT FILES

[[files]]
  stub = 'configs/stubs/golangci.yml'
  source = 'configs/templates/golangci.yml'
  destination = '.golangci.yml'

  #-------------------------------------------------------------------------------
  # KIRO DIRECTORY

[[files]]
  stub = 'configs/stubs/.kiro/steering/go-zero-diagnostics.md'
  destination = '.kiro/steering/go-zero-diagnostics.md'

  #-------------------------------------------------------------------------------
  # GITHUB DIRECTORY

  #-------------------------------------------------------------------------------
  # VSCODE DIRECTORY

[[files]]
  stub = 'configs/stubs/.vscode/extensions-golang.toml'
  source = 'configs/templates/.vscode/extensions-golang.toml'
  destination = '.vscode/extensions-golang.toml'

  [files.post_update_hook]
    bash = 'bash .vscode/extensions.sh'

    #-------------------------------------------------------------------------------
    # FILES WITH HOOKS

# Go tools
# https://go.dev/doc/modules/managing-dependencies#tools
[[files]]
  stub = 'configs/stubs/tools/Brewfile.golang'
  source = 'configs/templates/tools/Brewfile.golang'
  destination = 'tools/Brewfile.golang'
  executable = true

  [files.post_update_hook]
    bash = 'brew bundle --upgrade --upgrade-formulae --install --jobs=auto --file=tools/Brewfile.golang'
