// Copyright 2025-2026, Northwood Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cmd

import (
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/lithammer/dedent"
	"github.com/spf13/cobra"

	clihelpers "github.com/northwood-labs/cli-helpers"
)

type (
	lookupAccountResponse struct {
		SSOProfile string   `json:"sso_profile,omitzero"`
		AccountID  string   `json:"account_id"`
		Name       string   `json:"name"`
		Profiles   []string `json:"profiles"`
		Roles      []string `json:"roles"`
	}

	lookupRoleResponse struct {
		SSOProfile string   `json:"sso_profile,omitzero"`
		AccountID  string   `json:"account_id"`
		Name       string   `json:"name"`
		Query      string   `json:"query"`
		Matches    []string `json:"matches"`
	}
)

var (
	accountIDPattern = regexp.MustCompile(`^\d{12}$`)

	fLookupProfile string
	fLookupFor     string

	lookupCmd = &cobra.Command{
		Use:   "lookup",
		Short: "Lookup account and role information from local account cache.",
		Long: clihelpers.LongHelpText(`
		Lookup account and role information from local account cache.

		This command reads the list cache and the lookup index cache generated by
		the list command. It does not call AWS APIs.
		`),
		Args: cobra.NoArgs,
		Example: strings.TrimSpace(dedent.Dedent(`
		aws-sso-manager lookup account <account-identifier>
		aws-sso-manager lookup role <role-substring> --for <account-identifier>
		`)),
	}

	lookupAccountCmd = &cobra.Command{
		Use:   "account [account]",
		Short: "Resolve an account identifier to account details and valid roles.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			profileName, err := resolveLookupProfileName()
			if err != nil {
				return err
			}

			lookupIndex, err := loadOrBuildListAWSAccountsLookupIndex(listAWSAccountsInput{
				Logger:      logger,
				ProfileName: profileName,
			})
			if err != nil {
				return fmt.Errorf("could not load lookup cache: %w", err)
			}

			accountID, account, err := resolveLookupAccount(lookupIndex, args[0])
			if err != nil {
				return err
			}

			if fJSON {
				payload := lookupAccountResponse{
					SSOProfile: lookupIndex.ProfileName,
					AccountID:  accountID,
					Name:       account.Name,
					Profiles:   account.Profiles,
					Roles:      account.Roles,
				}

				data, err := json.Marshal(payload)
				if err != nil {
					return fmt.Errorf("could not marshal lookup account response to JSON: %w", err)
				}

				fmt.Println(string(data))

				return nil
			}

			fmt.Println(accountID)

			return nil
		},
	}

	lookupRoleCmd = &cobra.Command{
		Use:   "role [role] --for [account]",
		Short: "Lookup roles by case-insensitive substring within one account.",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if strings.TrimSpace(fLookupFor) == "" {
				return errors.New("flag --for is required")
			}

			profileName, err := resolveLookupProfileName()
			if err != nil {
				return err
			}

			lookupIndex, err := loadOrBuildListAWSAccountsLookupIndex(listAWSAccountsInput{
				Logger:      logger,
				ProfileName: profileName,
			})
			if err != nil {
				return fmt.Errorf("could not load lookup cache: %w", err)
			}

			accountID, account, err := resolveLookupAccount(lookupIndex, fLookupFor)
			if err != nil {
				return err
			}

			needle := strings.ToLower(strings.TrimSpace(args[0]))
			if needle == "" {
				return errors.New("role substring cannot be empty")
			}

			var matches []string
			for _, roleName := range account.Roles {
				if strings.Contains(strings.ToLower(roleName), needle) {
					matches = append(matches, roleName)
				}
			}

			sort.SliceStable(matches, func(i, j int) bool {
				return strings.ToLower(matches[i]) < strings.ToLower(matches[j])
			})

			if len(matches) == 0 {
				return fmt.Errorf("no roles matched %q for account %s (%s)", args[0], account.Name, accountID)
			}

			if fJSON {
				payload := lookupRoleResponse{
					SSOProfile: lookupIndex.ProfileName,
					AccountID:  accountID,
					Name:       account.Name,
					Query:      args[0],
					Matches:    matches,
				}

				data, err := json.Marshal(payload)
				if err != nil {
					return fmt.Errorf("could not marshal lookup role response to JSON: %w", err)
				}

				fmt.Println(string(data))

				return nil
			}

			for _, roleName := range matches {
				fmt.Println(roleName)
			}

			return nil
		},
	}
)

func resolveLookupProfileName() (string, error) {
	profileName := strings.TrimSpace(fLookupProfile)
	if profileName != "" {
		return profileName, nil
	}

	profileName = strings.TrimSpace(asvConfig.GetString("profile-name"))
	if profileName == "" {
		return "", errors.New("no profile configured; set profile-name in config or pass --profile")
	}

	return profileName, nil
}

func lookupAccountIDsByIdentifier(index listAWSAccountsLookupIndex, identifier string) ([]string, error) {
	trimmed := strings.TrimSpace(identifier)
	if trimmed == "" {
		return nil, errors.New("account identifier cannot be empty")
	}

	if accountIDPattern.MatchString(trimmed) {
		if _, ok := index.AccountsByID[trimmed]; ok {
			return []string{trimmed}, nil
		}
	}

	lookupKey := strings.ToLower(trimmed)

	if accountIDs := index.AccountIDsByProfileCI[lookupKey]; len(accountIDs) > 0 {
		return accountIDs, nil
	}

	if accountIDs := index.AccountIDsByNameCI[lookupKey]; len(accountIDs) > 0 {
		return accountIDs, nil
	}

	return nil, fmt.Errorf("account identifier %q not found", identifier)
}

func resolveLookupAccount(
	index listAWSAccountsLookupIndex,
	identifier string,
) (string, listAWSAccountsLookupAccount, error) {
	accountIDs, err := lookupAccountIDsByIdentifier(index, identifier)
	if err != nil {
		return "", listAWSAccountsLookupAccount{}, err
	}

	if len(accountIDs) > 1 {
		profileNote := ""
		if strings.TrimSpace(index.ProfileName) != "" {
			profileNote = fmt.Sprintf(" under SSO profile %q", index.ProfileName)
		}

		return "", listAWSAccountsLookupAccount{}, fmt.Errorf(
			"account identifier %q is ambiguous%s; matches account IDs: %s",
			identifier,
			profileNote,
			strings.Join(accountIDs, ", "),
		)
	}

	accountID := accountIDs[0]
	account, ok := index.AccountsByID[accountID]
	if !ok {
		return "", listAWSAccountsLookupAccount{}, fmt.Errorf(
			"account data is missing from lookup cache for ID %s",
			accountID,
		)
	}

	return accountID, account, nil
}

func init() {
	rootCmd.AddCommand(lookupCmd)

	lookupCmd.PersistentFlags().
		StringVarP(&fLookupProfile, "profile", "p", "", "SSO profile name used for cache lookups")
	lookupCmd.PersistentFlags().BoolVarP(&fJSON, "json", "j", false, "output in JSON format")

	lookupCmd.AddCommand(lookupAccountCmd)
	lookupCmd.AddCommand(lookupRoleCmd)

	lookupRoleCmd.Flags().StringVarP(
		&fLookupFor,
		"for",
		"f",
		"",
		"account identifier (account ID, account name, or profile name)",
	)
}
