// Copyright 2025-2026, Northwood Labs, LLC <license@northwood-labs.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cmd

import (
	"encoding/json"
	"fmt"
	"regexp"
	"slices"
	"strings"

	"github.com/lithammer/dedent"
	"github.com/spf13/cobra"

	clihelpers "github.com/northwood-labs/cli-helpers"
)

var (
	// AccountIDPattern is shared across lookup subcommands to distinguish a
	// 12-digit account ID from a human-readable name or profile identifier.
	accountIDPattern = regexp.MustCompile(`^\d{12}$`)

	fLookupProfile string
	fLookupFor     string

	// LookupCmd is the parent command. It reads exclusively from the local
	// lookup index cache — no AWS API calls — so it's fast and works offline.
	lookupCmd = &cobra.Command{
		Use:   "lookup",
		Short: "Lookup account and role information from local account cache.",
		Long: clihelpers.LongHelpText(`
		Lookup account and role information from local account cache.

		This command reads the list cache and the lookup index cache generated by
		the list command. It does not call AWS APIs.
		`),
		Args: cobra.NoArgs,
		Example: strings.TrimSpace(dedent.Dedent(`
		# Lookup an account by one of the identifiers.
		aws-sso-manager lookup account <account-identifier>

		# Lookup a role for a 12-digit AWS account.
		aws-sso-manager lookup role <role-substring> --for <account-identifier>
		`)),
	}

	// LookupAccountCmd resolves a flexible identifier (account ID, name, profile
	// name, or substring) to a single account. This flexibility lets users type
	// whatever they remember — "internal", "prod-admin", or the full 12-digit ID
	// — and get the canonical account ID back.
	lookupAccountCmd = &cobra.Command{
		Use:   "account [account]",
		Short: "Resolve an account identifier to account details and valid roles.",
		Args:  cobra.ExactArgs(1),
		Example: strings.TrimSpace(dedent.Dedent(`
		# Lookup an account by one of the identifiers.
		aws-sso-manager lookup account <account-identifier>
		`)),
		RunE: func(_ *cobra.Command, args []string) error {
			profileName, err := resolveLookupProfileName()
			if err != nil {
				return fmt.Errorf("could not resolve profile name: %w", err)
			}

			lookupIndex, err := loadOrBuildListAWSAccountsLookupIndex(&listAWSAccountsInput{
				Logger:      logger,
				ProfileName: profileName,
			})
			if err != nil {
				return fmt.Errorf("could not load lookup cache: %w", err)
			}

			accountID, account, err := resolveLookupAccount(lookupIndex, args[0])
			if err != nil {
				return fmt.Errorf("could not resolve account: %w", err)
			}

			if fJSON {
				payload := lookupAccountResponse{
					SSOProfile: lookupIndex.ProfileName,
					AccountID:  accountID,
					Name:       account.Name,
					Profiles:   account.Profiles,
					Roles:      account.Roles,
				}

				data, err := json.Marshal(payload)
				if err != nil {
					return fmt.Errorf("could not marshal lookup account response to JSON: %w", err)
				}

				fmt.Println(string(data))

				return nil
			}

			fmt.Println(accountID)

			return nil
		},
	}

	// LookupRoleCmd searches for roles by substring within a single account.
	// The --for flag is mandatory because role names are only meaningful in the
	// context of a specific account (the same role name can exist across many
	// accounts).
	lookupRoleCmd = &cobra.Command{
		Use:   "role [role] --for [account]",
		Short: "Lookup a role by case-insensitive substring within one account.",
		Args:  cobra.ExactArgs(1),
		Example: strings.TrimSpace(dedent.Dedent(`
		# Lookup a role by case-insensitive substring within one account.
		aws-sso-manager lookup role <role-substring> --for <account-identifier>
		`)),
		RunE: func(_ *cobra.Command, args []string) error {
			if strings.TrimSpace(fLookupFor) == "" {
				return ErrFlagForRequired
			}

			profileName, err := resolveLookupProfileName()
			if err != nil {
				return fmt.Errorf("could not resolve profile name: %w", err)
			}

			lookupIndex, err := loadOrBuildListAWSAccountsLookupIndex(&listAWSAccountsInput{
				Logger:      logger,
				ProfileName: profileName,
			})
			if err != nil {
				return fmt.Errorf("could not load lookup cache: %w", err)
			}

			accountID, account, err := resolveLookupAccount(lookupIndex, fLookupFor)
			if err != nil {
				return fmt.Errorf("could not resolve account: %w", err)
			}

			needle := strings.ToLower(strings.TrimSpace(args[0]))
			if needle == "" {
				return ErrRoleSubstringEmpty
			}

			matches := []string(nil)

			for _, roleName := range account.Roles {
				if strings.Contains(strings.ToLower(roleName), needle) {
					matches = append(matches, roleName)
				}
			}

			slices.SortStableFunc(matches, func(a, b string) int {
				return strings.Compare(strings.ToLower(a), strings.ToLower(b))
			})

			if len(matches) == 0 {
				return fmt.Errorf("%w: %q for account %s (%s)", ErrNoRolesMatched, args[0], account.Name, accountID)
			}

			if fJSON {
				payload := lookupRoleResponse{
					SSOProfile: lookupIndex.ProfileName,
					AccountID:  accountID,
					Name:       account.Name,
					Query:      args[0],
					Matches:    matches,
				}

				data, err := json.Marshal(payload)
				if err != nil {
					return fmt.Errorf("could not marshal lookup role response to JSON: %w", err)
				}

				fmt.Println(string(data))

				return nil
			}

			for _, roleName := range matches {
				fmt.Println(roleName)
			}

			return nil
		},
	}
)

type (
	// LookupAccountResponse is the JSON envelope for "lookup account --json".
	// It bundles everything a caller needs to identify and interact with an
	// account without making additional lookups.
	lookupAccountResponse struct {
		SSOProfile string   `json:"sso_profile,omitzero"` // lint:allow_format
		AccountID  string   `json:"account_id"`           // lint:allow_format
		Name       string   `json:"name"`
		Profiles   []string `json:"profiles"`
		Roles      []string `json:"roles"`
	}

	// LookupRoleResponse is the JSON envelope for "lookup role --json".
	// Including the query string lets callers correlate results with their input
	// when processing multiple lookups in a pipeline.
	lookupRoleResponse struct {
		SSOProfile string   `json:"sso_profile,omitzero"` // lint:allow_format
		AccountID  string   `json:"account_id"`           // lint:allow_format
		Name       string   `json:"name"`
		Query      string   `json:"query"`
		Matches    []string `json:"matches"`
	}
)

func init() { // lint:allow_init
	rootCmd.AddCommand(lookupCmd)

	lookupCmd.PersistentFlags().
		StringVarP(&fLookupProfile, "profile", "p", "", "SSO profile name used for cache lookups")
	lookupCmd.PersistentFlags().BoolVarP(&fJSON, "json", "j", false, "output in JSON format")

	lookupCmd.AddCommand(lookupAccountCmd)
	lookupCmd.AddCommand(lookupRoleCmd)

	lookupRoleCmd.Flags().StringVarP(
		&fLookupFor,
		"for",
		"f",
		"",
		"account identifier (account ID, account name, or profile name)",
	)
}

// resolveLookupProfileName determines which SSO profile to use for cache
// lookups. The --profile flag takes priority so scripts can target a specific
// profile without changing the config file.
func resolveLookupProfileName() (string, error) {
	profileName := strings.TrimSpace(fLookupProfile)
	if profileName != "" {
		return profileName, nil
	}

	profileName = strings.TrimSpace(asmConfig.GetString("profile-name"))
	if profileName == "" {
		return "", ErrNoProfileConfigured
	}

	return profileName, nil
}

// lookupAccountIDsByIdentifier resolves a user-provided identifier to one or
// more account IDs. The resolution order is intentional:
//
//  1. Exact 12-digit account ID — fastest, unambiguous.
//  2. Exact profile name (CI) — users often remember their profile aliases.
//  3. Exact account name (CI) — the human-readable AWS account name.
//  4. Substring match across names and profiles — catches partial input like
//     "internal" matching "internal-prod".
//
// Exact matches are tried first so that a user who types a full name always
// gets a single result, even if that name is also a substring of another.
func lookupAccountIDsByIdentifier( // lint:allow_complexity
	index listAWSAccountsLookupIndex,
	identifier string,
) ([]string, error) {
	trimmed := strings.TrimSpace(identifier)
	if trimmed == "" {
		return nil, ErrAccountIdentEmpty
	}

	// Exact match by 12-digit account ID.
	if accountIDPattern.MatchString(trimmed) {
		if _, ok := index.AccountsByID[trimmed]; ok {
			return []string{trimmed}, nil
		}
	}

	lookupKey := strings.ToLower(trimmed)

	// Exact match by profile name.
	if accountIDs := index.AccountIDsByProfileCI[lookupKey]; len(accountIDs) > 0 { // lint:allow_raw_number
		return accountIDs, nil
	}

	// Exact match by account name.
	if accountIDs := index.AccountIDsByNameCI[lookupKey]; len(accountIDs) > 0 { // lint:allow_raw_number
		return accountIDs, nil
	}

	// Substring match across account names and profile names. This is the
	// fallback that enables partial-name lookups like "internal" matching
	// "internal-prod". We deduplicate via a seen set because the same account
	// ID can appear in both name and profile maps.
	seen := make(map[string]struct{})

	var matched []string

	for nameKey, accountIDs := range index.AccountIDsByNameCI {
		if !strings.Contains(nameKey, lookupKey) {
			continue
		}

		for _, id := range accountIDs {
			if _, ok := seen[id]; !ok {
				seen[id] = struct{}{}
				matched = append(matched, id)
			}
		}
	}

	for profileKey, accountIDs := range index.AccountIDsByProfileCI {
		if !strings.Contains(profileKey, lookupKey) {
			continue
		}

		for _, id := range accountIDs {
			if _, ok := seen[id]; !ok {
				seen[id] = struct{}{}
				matched = append(matched, id)
			}
		}
	}

	if len(matched) > 0 { // lint:allow_raw_number
		slices.Sort(matched)
		return matched, nil
	}

	return nil, fmt.Errorf("%w: %q", ErrAccountIdentNotFound, identifier)
}

// resolveLookupAccount narrows the identifier down to exactly one account.
// Multiple matches are reported as an ambiguity error rather than silently
// picking one, because an incorrect account selection could lead to the user
// assuming the wrong role or accessing the wrong environment.
func resolveLookupAccount(
	index listAWSAccountsLookupIndex,
	identifier string,
) (string, listAWSAccountsLookupAccount, error) {
	accountIDs, err := lookupAccountIDsByIdentifier(index, identifier)
	if err != nil {
		return "", listAWSAccountsLookupAccount{}, fmt.Errorf("could not lookup account: %w", err)
	}

	if len(accountIDs) > 1 { // lint:allow_raw_number
		profileNote := ""
		if strings.TrimSpace(index.ProfileName) != "" {
			profileNote = fmt.Sprintf(" under SSO profile %q", index.ProfileName)
		}

		return "", listAWSAccountsLookupAccount{}, fmt.Errorf(
			"%w: %q%s; matches account IDs: %s",
			ErrAccountIdentAmbiguous,
			identifier,
			profileNote,
			strings.Join(accountIDs, ", "),
		)
	}

	accountID := accountIDs[0] // lint:allow_raw_number

	account, ok := index.AccountsByID[accountID]
	if !ok {
		return "", listAWSAccountsLookupAccount{}, fmt.Errorf(
			"%w: ID %s",
			ErrAccountDataMissing,
			accountID,
		)
	}

	return accountID, account, nil
}
