recommendations = [
  # @config-manager:start golang
  'casualjim.gotemplate',
  'golang.go',
  'maxmedia.go-prof',
  'msyrus.go-doc',
  'neverik.go-critic',
  'premparihar.gotestexplorer',
  'windmilleng.vscode-go-autotest',
  # @config-manager:end golang
]
